<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQlzgoho\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQlzgoho/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQlzgoho.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQlzgoho\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQlzgoho\appProdProjectContainer(array(
    'container.build_hash' => 'Qlzgoho',
    'container.build_id' => 'cca4c52a',
    'container.build_time' => 1519409383,
));
