<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdw1vry\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdw1vry/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXdw1vry.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXdw1vry\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXdw1vry\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xdw1vry',
    'container.build_id' => '3a0426ea',
    'container.build_time' => 1519139011,
));
